### ISSUE TITLE
Internal Server Error on signup

### ISSUE THREAD

**Issue by sardaukar** [delehef/hyades#1]
Hey, registered for a trial and after inputting my card details and authorizing Github's OAuth connection, got redirected to an "Internal Server Error" page :/

**Comment by delehef** [comment]
Hi and thanks for the report!

It should be fixed now, sorry for the inconvenience.

**Comment by sardaukar** [comment]
Thanks!

**Comment by sardaukar** [comment]
Getting a 502 now :/

**Comment by sardaukar** [comment]
And it's back - I've cancelled my subscription for now, until the service is a bit more stable :|

**Comment by delehef** [comment]
> until the service is a bit more stable :|

Yeah, one of your starred repos (gloomyson/starcraft) is under a DCMA takedown, so it choked on that.

My apologies that you had to deal with the teething problems :/
